package br.ulbra.view;

import br.ulbra.dao.ProdutoDAO;
import br.ulbra.entity.Produto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmCadProduto extends javax.swing.JFrame {

    /**
     * Creates new form FrmCadProduto
     */
    public FrmCadProduto() {
        initComponents();
    }

    public void carregarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) TBproduto.getModel();
        modelo.setRowCount(0); // limpa

        ProdutoDAO dao = new ProdutoDAO();
        for (Produto p : dao.listar()) {
            modelo.addRow(new Object[]{
                p.getNomeprod(),
                p.getDataCadProd(),
                p.getCategoriaprod(),
                p.getValorunitprod(),
                p.getQuantestoqueprod()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        TXTnomecad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TXTdata = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TXTcategoria = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TXTvalor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TXTquantidade = new javax.swing.JTextField();
        BTNsalvar = new javax.swing.JButton();
        BTNlimpar = new javax.swing.JButton();
        BTNcalcular = new javax.swing.JButton();
        BTNvoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBproduto = new javax.swing.JTable();
        BTNexcluir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("NOME");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("DATA");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("CATEGORIA");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("VALOR");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("QUANTIDADE ");

        BTNsalvar.setText("SALVAR");
        BTNsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNsalvarActionPerformed(evt);
            }
        });

        BTNlimpar.setText("LIMPAR");
        BTNlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNlimparActionPerformed(evt);
            }
        });

        BTNcalcular.setText("CALCULAR");
        BTNcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNcalcularActionPerformed(evt);
            }
        });

        BTNvoltar.setText("VOLTAR");
        BTNvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNvoltarActionPerformed(evt);
            }
        });

        TBproduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data", "Categoria", "Valor", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TBproduto);

        BTNexcluir.setText("EXCLUIR");
        BTNexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNexcluirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CADASTRO DE PRODUTOS");

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\aluno.saolucas\\Downloads\\letter-g_8999989 (1).png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(514, 514, 514)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(495, 495, 495)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TXTnomecad)
                                    .addComponent(TXTdata)
                                    .addComponent(TXTcategoria)
                                    .addComponent(TXTvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(TXTquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(459, 459, 459)
                            .addComponent(BTNsalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BTNcalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(BTNexcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BTNvoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BTNlimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(10, 10, 10))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(448, 448, 448)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(540, 540, 540))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TXTnomecad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TXTdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TXTcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TXTvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TXTquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNcalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNvoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNlimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNexcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNsalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNsalvarActionPerformed
        String nomeProduto = TXTnomecad.getText().trim();

// VALIDAÇÃO DO NOME
        if (nomeProduto.length() < 5) {
            JOptionPane.showMessageDialog(null, "O nome do produto deve ter no mínimo 5 caracteres.");
            return;
        }

        if (!nomeProduto.matches("[a-zA-ZÀ-ÿ\\s]+")) {
            JOptionPane.showMessageDialog(null, "O nome do produto deve conter apenas letras e espaços (sem números ou símbolos).");
            return;
        }

// CONTINUA SE TUDO ESTIVER CERTO
        Produto prod = new Produto();
        prod.setNomeprod(nomeProduto);
        prod.setDataCadProd(TXTdata.getText());
        prod.setCategoriaprod(TXTcategoria.getText());
        prod.setValorunitprod(Double.parseDouble(TXTvalor.getText()));
        prod.setQuantestoqueprod(Integer.parseInt(TXTquantidade.getText()));

        System.out.println("SALVANDO PRODUTO..."); // <-- ajuda a debugar

        ProdutoDAO dao = new ProdutoDAO();
        boolean sucesso = dao.salvar(prod); // só 1 chamada

        if (sucesso) {
            carregarTabela();
            JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso!");
        }


           }//GEN-LAST:event_BTNsalvarActionPerformed

    private void BTNcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNcalcularActionPerformed

        try {
            Produto prod = new Produto();

            // Aqui você deve pegar os valores dos campos da tela (exemplo)
            prod.setValorunitprod(Double.parseDouble(TXTvalor.getText()));
            prod.setQuantestoqueprod(Integer.parseInt(TXTquantidade.getText()));

            double totalEstoque = prod.calcularEstoque();

            JOptionPane.showMessageDialog(null, "Valor total em estoque: R$ " + totalEstoque);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Erro nos valores inseridos: " + ex.getMessage());
        }

    }//GEN-LAST:event_BTNcalcularActionPerformed

    private void BTNvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNvoltarActionPerformed
        FrmDashBoard telaPrincipal = new FrmDashBoard();
        telaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNvoltarActionPerformed

    private void BTNexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNexcluirActionPerformed

        int linhaSelecionada = TBproduto.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
            return;
        }

        // Pegando o nome do produto da tabela — coluna 1 (ajuste se necessário)
        String nome = TBproduto.getValueAt(linhaSelecionada, 0).toString();

        int confirmacao = JOptionPane.showConfirmDialog(null,
                "Deseja realmente excluir o produto '" + nome + "'?",
                "Confirmação de Exclusão",
                JOptionPane.YES_NO_OPTION);

        if (confirmacao == JOptionPane.YES_OPTION) {
            ProdutoDAO dao = new ProdutoDAO();
            if (dao.excluirPorNome(nome)) {
                carregarTabela(); // atualiza a tabela
            }

        }


    }//GEN-LAST:event_BTNexcluirActionPerformed

    private void BTNlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNlimparActionPerformed
        TXTnomecad.setText("");
        TXTdata.setText("");
        TXTcategoria.setText("");
        TXTvalor.setText("");
        TXTquantidade.setText("");

        TXTnomecad.requestFocus();
    }//GEN-LAST:event_BTNlimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNcalcular;
    private javax.swing.JButton BTNexcluir;
    private javax.swing.JButton BTNlimpar;
    private javax.swing.JButton BTNsalvar;
    private javax.swing.JButton BTNvoltar;
    private javax.swing.JTable TBproduto;
    private javax.swing.JTextField TXTcategoria;
    private javax.swing.JTextField TXTdata;
    private javax.swing.JTextField TXTnomecad;
    private javax.swing.JTextField TXTquantidade;
    private javax.swing.JTextField TXTvalor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
